# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.0.0"

gem "itamae"

group :development, :test do
  gem "rubocop"
  gem "rubocop-performance"
end

group :development do
  gem "solargraph"
end
